# -*- coding: utf-8 -*-
# vim: ft=yaml
---
###############################################################################
# Define all YAML node anchors
###############################################################################
.node_anchors:
  # `only` (also used for `except` where applicable)
  only_branch_master_parent_repo: &only_branch_master_parent_repo
    - 'master@saltstack-formulas/postfix-formula'
  # `stage`
  stage_lint: &stage_lint 'lint'
  stage_release: &stage_release 'release'
  stage_test: &stage_test 'test'
  # `image`
  # yamllint disable rule:line-length
  image_commitlint: &image_commitlint 'techneg/ci-commitlint:v1.1.87@sha256:7d88b7ea69f3cd917995d0e7ea5ce7aae97383db95003319d0c43a1d68372402'
  image_dindruby: &image_dindruby 'techneg/ci-docker-python-ruby:v2.2.56@sha256:ff9bbcb82cc2b4ce5c322e45a5afe2a952cf2a418e13aa4b57bf5609f854a0d4'
  image_dindrubybionic: &image_dindrubybionic 'techneg/ci-docker-python-ruby:v2.2.56@sha256:ff9bbcb82cc2b4ce5c322e45a5afe2a952cf2a418e13aa4b57bf5609f854a0d4'
  image_precommit: &image_precommit 'techneg/ci-pre-commit:v2.4.21@sha256:620cdfaa9c45b4941090e2b557f5f551fbc1189caf13689e5bbfbd5c76885400'
  image_rubocop: &image_rubocop 'pipelinecomponents/rubocop:latest@sha256:fe69f9642c7edde46bbd78326d2c42c6e13fc73694efb142e92e206725479328'
  image_semantic-release: &image_semanticrelease 'myii/ssf-semantic-release:15.14@sha256:374f588420087517a3cc0235e11293bffd72d7a59da3d98d5e69f014ff2a7761'
  # `services`
  services_docker_dind: &services_docker_dind
    - 'docker:dind@sha256:3a861ec98623bd6014610291123751dc19e0c6d474ac3b38767771791ac0eb5e'
  # yamllint enable rule:line-length
  # `variables`
  # https://forum.gitlab.com/t/gitlab-com-ci-caching-rubygems/5627/3
  # https://bundler.io/v1.16/bundle_config.html
  variables_bundler: &variables_bundler
    BUNDLE_CACHE_PATH: '${CI_PROJECT_DIR}/.cache/bundler'
    BUNDLE_WITHOUT: 'production'
  # `cache`
  cache_bundler: &cache_bundler
    key: '${CI_JOB_STAGE}'
    paths:
      - '${BUNDLE_CACHE_PATH}'

###############################################################################
# Define stages and global variables
###############################################################################
stages:
  - *stage_lint
  - *stage_test
  - *stage_release
variables:
  DOCKER_DRIVER: 'overlay2'

###############################################################################
# `lint` stage: `commitlint`, `pre-commit` & `rubocop` (latest, failure allowed)
###############################################################################
commitlint:
  stage: *stage_lint
  image: *image_commitlint
  script:
    # Add `upstream` remote to get access to `upstream/master`
    - 'git remote add upstream
       https://gitlab.com/saltstack-formulas/postfix-formula.git'
    - 'git fetch --all'
    # Set default commit hashes for `--from` and `--to`
    - 'export COMMITLINT_FROM="$(git merge-base upstream/master HEAD)"'
    - 'export COMMITLINT_TO="${CI_COMMIT_SHA}"'
    # `coqbot` adds a merge commit to test PRs on top of the latest commit in
    # the repo; amend this merge commit message to avoid failure
    - |
      if [ "${GITLAB_USER_LOGIN}" = "coqbot" ] \
      && [ "${CI_COMMIT_BRANCH}" != "master" ]; then
        git commit --amend -m \
          'chore: reword coqbot merge commit message for commitlint'
        export COMMITLINT_TO=HEAD
      fi
    # Run `commitlint`
    - 'commitlint --from "${COMMITLINT_FROM}"
                  --to   "${COMMITLINT_TO}"
                  --verbose'

pre-commit:
  stage: *stage_lint
  image: *image_precommit
  # https://pre-commit.com/#gitlab-ci-example
  variables:
    PRE_COMMIT_HOME: '${CI_PROJECT_DIR}/.cache/pre-commit'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - '${PRE_COMMIT_HOME}'
  script:
    - 'pre-commit run --all-files --color always --verbose'

# Use a separate job for `rubocop` other than the one potentially run by `pre-commit`
# - The `pre-commit` check will only be available for formulas that pass the default
#   `rubocop` check -- and must continue to do so
# - This job is allowed to fail, so can be used for all formulas
# - Furthermore, this job uses all of the latest `rubocop` features & cops,
#   which will help when upgrading the `rubocop` linter used in `pre-commit`
rubocop:
  allow_failure: true
  stage: *stage_lint
  image: *image_rubocop
  script:
    - 'rubocop -d -P -S --enable-pending-cops'

###############################################################################
# Define `test` template
###############################################################################
.test_instance: &test_instance
  stage: *stage_test
  image: *image_dindruby
  services: *services_docker_dind
  variables: *variables_bundler
  cache: *cache_bundler
  before_script:
    # TODO: This should work from the env vars above automatically
    - 'bundle config set path "${BUNDLE_CACHE_PATH}"'
    - 'bundle config set without "${BUNDLE_WITHOUT}"'
    - 'bundle install'
  script:
    # Alternative value to consider: `${CI_JOB_NAME}`
    - 'bin/kitchen verify "${DOCKER_ENV_CI_JOB_NAME}"'

###############################################################################
# Define `test` template (`allow_failure: true`)
###############################################################################
.test_instance_failure_permitted:
  <<: *test_instance
  allow_failure: true

###############################################################################
# `test` stage: each instance below uses the `test` template above
###############################################################################
## Define the rest of the matrix based on Kitchen testing
# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
# yamllint disable rule:line-length
# Fedora 41+ will permit failure until this PR is merged into kitchen-docker
# https://github.com/test-kitchen/kitchen-docker/pull/427 is merged
# OpenSUSE master branch will fail until zypperpkg module is back in salt core
# https://github.com/saltstack/great-module-migration/issues/14
#
# The alias states were removed in the great module migration, causing the tests to fail with Salt master branch
# See https://github.com/saltstack-formulas/postfix-formula/issues/134
debian-12-master-py3: {extends: '.test_instance_failure_permitted'}
debian-11-master-py3: {extends: '.test_instance_failure_permitted'}
ubuntu-2404-master-py3: {extends: '.test_instance_failure_permitted'}
ubuntu-2204-master-py3: {extends: '.test_instance_failure_permitted'}
ubuntu-2004-master-py3: {extends: '.test_instance_failure_permitted'}
centos-stream9-master-py3: {extends: '.test_instance_failure_permitted'}
opensuse-leap-156-master-py3: {extends: '.test_instance_failure_permitted'}
opensuse-leap-155-master-py3: {extends: '.test_instance_failure_permitted'}
fedora-41-master-py3: {extends: '.test_instance_failure_permitted'}
fedora-40-master-py3: {extends: '.test_instance_failure_permitted'}
debian-12-3007-1-py3: {extends: '.test_instance'}
debian-11-3007-1-py3: {extends: '.test_instance'}
ubuntu-2404-3007-1-py3: {extends: '.test_instance'}
ubuntu-2204-3007-1-py3: {extends: '.test_instance'}
ubuntu-2004-3007-1-py3: {extends: '.test_instance'}
centos-stream9-3007-1-py3: {extends: '.test_instance'}
opensuse-leap-156-3007-1-py3: {extends: '.test_instance'}
opensuse-leap-155-3007-1-py3: {extends: '.test_instance'}
fedora-41-3007-1-py3: {extends: '.test_instance_failure_permitted'}
fedora-40-3007-1-py3: {extends: '.test_instance'}
debian-12-3006-10-py3: {extends: '.test_instance'}
debian-11-3006-10-py3: {extends: '.test_instance'}
ubuntu-2404-3006-10-py3: {extends: '.test_instance'}
ubuntu-2204-3006-10-py3: {extends: '.test_instance'}
ubuntu-2004-3006-10-py3: {extends: '.test_instance'}
opensuse-leap-156-3006-10-py3: {extends: '.test_instance'}
opensuse-leap-155-3006-10-py3: {extends: '.test_instance'}
fedora-41-3006-10-py3: {extends: '.test_instance_failure_permitted'}
fedora-40-3006-10-py3: {extends: '.test_instance'}
# yamllint enable rule:line-length

###############################################################################
# `release` stage: `semantic-release`
###############################################################################
semantic-release:
  only: *only_branch_master_parent_repo
  stage: *stage_release
  image: *image_semanticrelease
  variables:
    MAINTAINER_TOKEN: '${GH_TOKEN}'
  script:
    # Update `AUTHORS.md`
    - '${HOME}/go/bin/maintainer contributor'
    # Run `semantic-release`
    - 'semantic-release'
